### ISSUE TITLE
Don't work with django-modeltranslation

### ISSUE THREAD

**Issue by mklymyshyn** [kmmbvnr/django-any#3]
django_any don't work with django-modeltranslation which is sad. Below is traceback with details:

```
Traceback (most recent call last):
  File "/home/max/testproject/tweets/tests.py", line 77, in test_widget
    content = any_model(Content, slug='test', title='Test')
  File "/home/max/.testprojectenv/lib/python2.6/site-packages/django_any/functions.py", line 90, in __call__
    return self._create_value(*args, **kwargs)
  File "/home/max/.testprojectenv/lib/python2.6/site-packages/django_any/functions.py", line 87, in _create_value
    return function(*args, **kwargs)
  File "/home/max/.testprojectenv/lib/python2.6/site-packages/django_any/models.py", line 441, in any_model_default
    _fill_model_fields(result, **kwargs)
  File "/home/max/.testprojectenv/lib/python2.6/site-packages/django_any/models.py", line 431, in _fill_model_fields
    setattr(model, field.name, any_field(field, **fields_args[field.name]))
  File "/home/max/.testprojectenv/lib/python2.6/site-packages/django_any/functions.py", line 90, in __call__
    return self._create_value(*args, **kwargs)
  File "/home/max/.testprojectenv/lib/python2.6/site-packages/django_any/models.py", line 53, in wrapper
    return function(field, **kwargs)
  File "/home/max/.testprojectenv/lib/python2.6/site-packages/django_any/models.py", line 36, in wrapper
    return function(field, **kwargs)
  File "/home/max/.testprojectenv/lib/python2.6/site-packages/django_any/functions.py", line 85, in _create_value
    raise TypeError("no match %s" % field_type)
TypeError: no match <class 'modeltranslation.fields.TranslationField'>
```

**Comment by kmmbvnr** [comment]
django-any supports only known fields.

You should define custom data generator for `modeltranslation.fields.TranslationField`

Use django.any_any_field.register decorator. See django_any.models for sample code

Or just specify value in any_model call explicitly.

**Comment by mklymyshyn** [comment]
Thank you, it helps
